"""empty message

Revision ID: 50daf7977b8d
Revises: eb65ed96aaf5
Create Date: 2017-07-27 00:00:15.193189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50daf7977b8d'
down_revision = 'eb65ed96aaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
